//Users
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_USERS = 'GET_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL';
export const USER_LOADED_BY_EMAIL = 'USER_LOADED_BY_EMAIL';
export const USER_LOADED_BY_EMAIL_FAIL = 'USER_LOADED_BY_EMAIL_FAIL';

//Posts
export const GET_POSTS = 'GET_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const DELETE_POST = 'DELETE_POST';
export const VIEWS_POST = 'VIEWS_POST';
export const LOVED_POST = 'LOVED_POST';
export const UNLOVED_POST = 'UNLOVED_POST';
export const EDIT_CHAPTER_FROM_POST_DELETE = 'EDIT_CHAPTER_FROM_POST_DELETE';
export const EDIT_CHAPTER_FROM_POST_ADD = 'EDIT_CHAPTER_FROM_POST_ADD';
export const EDIT_CHAPTER_FROM_POST_EDIT = 'EDIT_CHAPTER_FROM_POST_EDIT';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';

//Comments
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const REPLY_COMMENT = 'REPLY_COMMENT';
export const REPLY_COMMENT_FAIL = 'REPLY_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const LOVED_COMMENT = 'LOVED_COMMENT';
export const UNLOVED_COMMENT = 'UNLOVED_COMMENT';

//Manga
export const GET_MANGAS = 'GET_MANGAS';
export const ADD_MANGA = 'ADD_MANGA';
export const DELETE_MANGA = 'DELETE_MANGA';
export const MANGAS_LOADING = 'MANGAS_LOADING';
export const ADD_MANGA_SUCCESS = "ADD_MANGA_SUCCESS";
export const ADD_MANGA_FAIL = "ADD_MANGA_FAIL";
export const EDIT_MANGA = "EDIT_MANGA";
export const EDIT_MANGA_FAIL = "EDIT_MANGA_FAIL";

//CHAPTERS
export const GET_CHAPTERS = 'GET_CHAPTERS';
export const ADD_CHAPTER = 'ADD_CHAPTER';
export const DELETE_CHAPTER = 'DELETE_CHAPTER';
export const CHAPTERS_LOADING = 'CHAPTERS_LOADING';
export const ADD_CHAPTER_SUCCESS = "ADD_CHAPTER_SUCCESS";
export const ADD_CHAPTER_FAIL = "ADD_CHAPTER_FAIL";
export const EDIT_CHAPTER = "EDIT_CHAPTER";
export const EDIT_CHAPTER_FAIL = "EDIT_CHAPTER_FAIL";
export const UPDATE_CHAPTER = "UPDATE_CHAPTER";

//Errors and msgs
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_MSGS = 'GET_MSGS';
export const CLEAR_MSGS = 'CLEAR_MSGS';
export const DELETE_FAIL = 'DELETE_FAIL';

//TwoFactorAuthentication
export const CREATE_TOKEN = 'CREATE_TOKEN';
export const CREATE_TOKEN_FAIL = 'CREATE_TOKEN_FAIL';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const VERIFY_TOKEN_FAIL = 'VERIFY_TOKEN_FAIL';

//Contact
export const MAIL_SEND = 'MAIL_SEND';
export const MAIL_SEND_FAIL = 'MAIL_SEND_FAIL';

//Subscribe
export const GET_SUBSCRIBES = 'GET_SUBSCRIBES';
export const ADD_SUBSCRIBE = 'ADD_SUBSCRIBE';
export const DELETE_SUBSCRIBE = 'DELETE_SUBSCRIBE';
export const SUBSCRIBES_LOADING = 'SUBSCRIBES_LOADING';
export const ADD_SUBSCRIBE_SUCCESS = "ADD_SUBSCRIBE_SUCCESS";
export const ADD_SUBSCRIBE_FAIL = "ADD_SUBSCRIBE_FAIL";

//Setting
export const GET_SETTINGS = 'GET_SETTINGS';
export const SETTINGS_LOADING = 'SETTINGS_LOADING';
export const SETTING_FAIL = "EDIT_SETTINGS_FAIL";
export const SET_ATT_HEADER = "SET_ATT_HEADER";
export const SET_MYVISION = "SET_MYVISION";
export const SET_BG_IMAGE = "SET_BG_IMAGE";
export const SET_LOGO_IMAGE = "SET_LOGO_IMAGE";
export const SET_COVERBOOK_IMAGE = "SET_COVERBOOK_IMAGE"; 
export const EDIT_SETTINGS = "EDIT_SETTINGS"; 

//Character
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTERS_LOADING = 'CHARACTERS_LOADING';
export const ADD_CHARACTER = "ADD_CHARACTER";
export const ADD_CHARACTER_FAIL = "ADD_CHARACTER_FAIL";
export const EDIT_CHARACTER = "EDIT_CHARACTER";
export const EDIT_CHARACTER_FAIL = "EDIT_CHARACTER_FAIL";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const DELETE_CHARACTER_FAIL = "DELETE_CHARACTER_FAIL";
export const GET_CHARACTER_BY_ID = "GET_CHARACTER_BY_ID";
export const EDIT_SINGAL_CHARACTER = "EDIT_SINGAL_CHARACTER";
export const ADD_PROP_CHARACTER_FAIL = "ADD_PROP_CHARACTER_FAIL";
export const DELETE_PROP_CHARACTER = "DELETE_PROP_CHARACTER";
export const DELETE_PROP_CHARACTER_FAIL = "DELETE_PROP_CHARACTER_FAIL";